export const NODE_TYPES = {
  hud: 'hud',
  hudLink: 'hud-link',
  hudHtml: 'hud-html',
  hudHtmlLink: 'hud-html-link',
  image: 'image',
  imageLink: 'image-link',
  light: 'light',
  lightLink: 'light-link',
  object: 'object',
  objectLink: 'object-link',
  objectHud: 'object-hud',
  objectHudLink: 'object-hud-link',
  objectGroup: 'object-group',
  objectGroupLink: 'object-group-link',
  video: 'video',
  videoLink: 'video-link',
  camera: 'camera',
  configuration: 'configuration',
  folder: 'folder',
  javascript: 'javascript',
  stylesheet: 'stylesheet',
  hdr: 'hdr',
} as const;
