import { ShaderParameterType, ShaderValue } from '..';

export const initialMaterialValues: Record<ShaderParameterType, ShaderValue> = {
  albedo_ratio: [255, 255, 255],
  albedo_texture: '',
  albedo_video: '',
  ambient_ratio: [255, 255, 255],
  ambient_texture: '',
  ambient_video: '',
  ao_ratio: 1,
  ao_texture: '',
  ao_texture_channel: 'r',
  diffuse_ibl_ratio: [255, 255, 255],
  diffuse_ratio: [255, 255, 255],
  diffuse_texture: '',
  emissive_ratio: [0, 0, 0],
  emissive_texture: '',
  extent: [0, 0, 0],
  metalness_ratio: 1,
  metalness_texture: '',
  metalness_texture_channel: 'r',
  normal_ratio: 1,
  normal_texture: '',
  opacity_ratio: 1,
  opacity_texture: '',
  opacity_texture_channel: 'a',
  roughness_ratio: 1,
  roughness_texture: '',
  roughness_texture_channel: 'r',
  specular_ibl_ratio: [255, 255, 255],
  specular_pbr_ratio: [255, 255, 255],
  specular_power: 32,
  specular_ratio: [255, 255, 255],
  specular_texture: '',
  use_alpha_channel: false,
  use_pbr: true,
  uv_animation: 0,
};
